# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Quakers in Hungary

# Uncomment the lines below to configure your website in a second language.
hu:
  languageCode: hu
  contentDir: content/hu
  title: Kvékerek Magyarországon
  params:
    description: Kvékerek Magyarországon
  menu:
    main:
     - name: Home
       url: /#top
       weight: 10
     - name: Features
       url: /#features
       weight: 20
     - name: Meetings
       url: /#solutions
       weight: 30
     - name: Resources
       weight: 40
       hasChildren: true
     - parent: Resources
       name: Blog
       url: blog/
